version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
      nodejs: 20

  pre_build:
    commands:
      - echo "Detecting changed Lambda functions"

      - |
        CHANGED_LAMBDAS=$(git diff --name-only HEAD~1 HEAD \
          | grep '^lambdas/' \
          | cut -d/ -f2 \
          | sort -u)

        if [ -z "$CHANGED_LAMBDAS" ]; then
          echo "No Lambda changes detected. Exiting."
          exit 0
        fi

        echo "Changed Lambdas:"
        echo "$CHANGED_LAMBDAS"

  build:
    commands:
      - |
        for FUNCTION_NAME in $CHANGED_LAMBDAS; do
          echo "Deploying $FUNCTION_NAME"

          cd "lambdas/$FUNCTION_NAME"

          # Python Lambda
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt -t .
          fi

          # Node Lambda
          if [ -f package.json ]; then
            npm install --production
          fi

          zip -r "$FUNCTION_NAME.zip" .

          aws lambda update-function-code \
            --function-name "$FUNCTION_NAME" \
            --zip-file fileb://"$FUNCTION_NAME.zip"

          cd -
        done
