AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  LambdaCodeVersion:
    Type: String
    Description: "S3 Object Version of Lambda zip"

Resources:
  test:
    Type: AWS::Lambda::Function
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      FunctionName: test
      Runtime: python3.12
      Handler: lambda_function.lambda_handler
      Role: arn:aws:iam::398069592832:role/service-role/test-role-spgvkicv
      Timeout: 3
      MemorySize: 128
      Architectures:
        - x86_64
      Code:
        S3Bucket: rushi2424
        S3Key: test.zip
        S3ObjectVersion: !Ref LambdaCodeVersion
